### ISSUE TITLE
All Controllers use the same alias?

### ISSUE THREAD

**Issue by dmitriz** [gordonmzhu/angular-course-demo-app-v2#1]
Just been reading through the code and found it hard to understand where each `vm` comes from. 
Every single controller seems to be aliased `vm`! 
Was hoping to learn some best practices but this doesn't seem to be one. 
Or is it?

**Comment by gordonmzhu** [comment]
Hey Dmitri. The 'vm' alias is taken directly from the angular-styleguide. Here's a link to the relevant section:

https://github.com/johnpapa/angular-styleguide#style-y032

**Comment by dmitriz** [comment]
I don't see any recommendation to use the same alias for different controllers. In fact, it makes it very hard to distinguish them.

**Comment by gordonmzhu** [comment]
Pasted from permalink in my previous comment:

[Style Y032]

Use a capture variable for this when using the controllerAs syntax. Choose a consistent variable name such as vm, which stands for ViewModel.

Why?: The this keyword is contextual and when used within a function inside a controller may change its context. Capturing the context of this avoids encountering this problem.

```javascript
/* avoid */
function CustomerController() {
    this.name = {};
    this.sendMessage = function() { };
}
/* recommended */
function CustomerController() {
    var vm = this;
    vm.name = {};
    vm.sendMessage = function() { };
}
```

Note: You can avoid any jshint warnings by placing the comment above the line of code. However it is not needed when the function is named using UpperCasing, as this convention means it is a constructor function, which is what a controller is in Angular.

```javascript
/* jshint validthis: true */
var vm = this;
Note: When creating watches in a controller using controller as, you can watch the vm.* member using the following syntax. (Create watches with caution as they add more load to the digest cycle.)

<input ng-model="vm.title"/>
function SomeController($scope, $log) {
    var vm = this;
    vm.title = 'Some Title';

    $scope.$watch('vm.title', function(current, original) {
        $log.info('vm.title was %s', original);
        $log.info('vm.title is now %s', current);
    });
}
```

Note: When working with larger codebases, using a more descriptive name can help ease cognitive overhead & searchability. Avoid overly verbose names that are cumbersome to type.

```javascript
<!-- avoid -->
<input ng-model="customerProductItemVm.text">
<!-- recommended -->
<input ng-model="productVm.id">
```

**Comment by dmitriz** [comment]
I find this actually important recommendation:

*Note: When working with larger codebases, using a more descriptive name can help ease cognitive overhead & searchability. Avoid overly verbose names that are cumbersome to type.*

`vm` is descriptive for only one controller, then it stops being so and **cognitive overhead & searchability** quickly becomes an issue. `vm` is only good for tiny basic code snippets. Anything beyond should be treated as "large codebase" with best practices promoted as people are going to use your example for writing their large code. 

This code is by no means small, it is a complete app with multiple files and directories, and is the major example linked from Firebase Guide.

**Comment by gordonmzhu** [comment]
If you'd like to have different names for each view model, it's an absolutely valid approach. I find that using different variable names for each view model is most useful if you have several view models in a single template. When that happens, having 'vm' refer to different objects gets really confusing. This is less dependent on the size of your app and more dependent on your coding style.

This app avoids this by having a separate templates for each view model so it's less of an issue. And if you follow this practice, consistently naming your view models 'vm' works very well. 

If you're still interested in this, check out some of the example apps in John Papa's Github account (the author of the angular style guide). He uses 'vm' consistently and is also able to avoid confusion by having different templates for each view model (like I've done in this app).

**Comment by dmitriz** [comment]
I can see that it may work if you stick hard to the policy of never using multiple controllers in the same template. But I find it a fragile solution, as things will break as soon as you (or someone else working on the code) forgets it:
```  
<p ng-controller="Out as vm">
    Out: {{vm.outer}}
    <p ng-controller="In as vm">
      In: {{vm.outer}}
    </p>
  </p>
```
http://jsbin.com/xijebi/edit?html,js,output

Another problem is the template or controller re-use.
Now there is no more one-to-one relation and it becomes harder and harder to track which one belongs to which. 

I am looking for a robust solution that won't show any surprises even if I break any unwritten rules.

People come here to learn code best practices but they can easily miss those rules without which their code would break.
