### ISSUE TITLE
Token expiration

### ISSUE THREAD

**Issue by petrusek** [gordonmzhu/angular-course-demo-app-v2#2]
Hi,
I've been going through this demo app, it looks very nice and clean, but it is not handling token expiration (while the user is logged in). You can test it by shortening the session length (to e.g. 10 seconds) in Firebase.

Is there some best practice, how to **prolong the session of active users**, and how to **properly log out users** once their session (token) expires?

Your demo just hides all data on the /waitlist page, throws a warning + error... but user can log in again and regain access.

```
FIREBASE WARNING: auth() was canceled: Auth token is expired. 
Error: permission_denied: Client doesn't have permission to access the desired data.
```

**Comment by gordonmzhu** [comment]
Thanks for pointing out this problem Tom.

I would probably just log the user out and then say that they need to log-in again. That would probably be the simplest solution. There are of course other solutions as well, but given that few people will ever be in this scenario, just telling people their session expired and they need to log-in again would work fine.

If you're curious, I'd also try emailing the firebase google group to see if anyone else has any suggestions too. In any case, I'll take a careful look at this in the next few days and add my own solution and will resolve this issue at that time.

**Comment by petrusek** [comment]
The main problem is in correctly "unsubscribing" from db changes, which is imho quite hard (and if not hard, then at least unclear). For small projects it is probably just a small issue, but for bigger projects (websites) it can get quite noticeable. Consider browsing through all pages of a huge website, so you instantiated all controllers, registered $firebaseObjects for each part of the database you can see... after a while, even if all the controllers are gone, the $firebaseObjects keep syncing the data, because they haven't been .$destroy()-ed. (I'm not sure if it could be an intention to allow some kind of "offline" access.)

I'm experimenting with ±this approach
```javascript
  // controller's constructor

  // attach auth listener - in all controllers requiring auth :-(
  this.Auth.$onAuth(function(authData) {
    if (!authData) {
      $state.go('login'); // in case token expired, redirect to login
    }
  });

  // register "destructor"
  this.$scope.$on('$destroy', this.destroy.bind(this));
```

And I also have a "destructor"
```javascript
SomeController.prototype.destroy = function() {
  // destroy the synced firebase object
  this.data.$destroy();
};
```

The problem is, it is quite a lot of writing and I'm not sure if it is good/bad, or if it could be somehow generalized.
I'm quite new to these things and I find all the examples extremely simple. What I like about your demo app is, that it's doing more than just plain one-to-one mapping of the documentation. Thank you for sharing your ideas ;-).

**Comment by gordonmzhu** [comment]
Hey Tom. So I pushed two commits that address your issues:

1) Token expiration: https://github.com/gordonmzhu/angular-course-demo-app-v2/commit/96987ddc1183d83c490b53fad335bad20edb052c

2) Destroying listeners on logout: https://github.com/gordonmzhu/angular-course-demo-app-v2/commit/e7c45209bf3168615461decceeea9820d6c9d8e6

**Comment by gordonmzhu** [comment]
If you want a nice video walkthrough of #2, destroying listeners on logout, I added it as a video in angularcourse.com. I'll probably add a video that covers #1 soon too.
