### ISSUE TITLE
Does not work with the new firebase

### ISSUE THREAD

**Issue by thekemp** [gordonmzhu/angular-course-demo-app-v2#3]
This sample does not appear to work with the new firebase is a new sample available?

**Comment by gordonmzhu** [comment]
I'll post a change soon that uses the latest Firebase and AngularFire.

**Comment by gordonmzhu** [comment]
Fixed with https://github.com/gordonmzhu/angular-course-demo-app-v2/commit/8f0b745451413efc35b1bb4ade06c0cf3497aef0
